import Runtime.Transport
import Runtime.VM.Model.State


/-! # Handler Equivalence

Effect-handler equivalence theorem for protocol outcomes:
if two handlers satisfy the same handler contract, their outcomes are
observationally equivalent.
-/

set_option autoImplicit false

section

universe u

/-- Observable protocol outcome extracted from a transport trace. -/
structure ProtocolOutcome (ν ε : Type u) [VerificationModel ν] [EffectRuntime ε] where
  transportTrace : TransportTrace ν
  obsTrace : List (ObsEvent ε)
  completed : Bool

/-- Observational equivalence on outcomes: same visible trace and completion bit. -/
def ProtocolOutcome.ObservationalEq {ν ε : Type u} [VerificationModel ν] [EffectRuntime ε]
    (o₁ o₂ : ProtocolOutcome ν ε) : Prop :=
  o₁.obsTrace = o₂.obsTrace ∧ o₁.completed = o₂.completed

/-- Contract that an effect handler must satisfy. -/
structure HandlerContract (ν ε : Type u) [VerificationModel ν] [EffectRuntime ε] where
  /-- Transport-level behavioral specification. -/
  spec : TransportSpec ν
  /-- Protocol outcome function induced by a handler-observable trace. -/
  outcome : TransportTrace ν → ProtocolOutcome ν ε
  /-- Any two traces satisfying the contract are observationally indistinguishable. -/
  observationalDeterminism :
    ∀ t₁ t₂, SpecSatisfied spec t₁ → SpecSatisfied spec t₂ →
      ProtocolOutcome.ObservationalEq (outcome t₁) (outcome t₂)

/-- A concrete handler satisfies a contract when all its induced traces satisfy `spec`. -/
def HandlerModelsContract (ν ε : Type u) [VerificationModel ν] [EffectRuntime ε]
    (handler : HandlerId) (contract : HandlerContract ν ε) : Prop :=
  ∀ handlers trace, IsHandlerTrace handler handlers trace → SpecSatisfied contract.spec trace

/-- The canonical trace generated by `handlerTraceOf` is a handler trace. -/
theorem isHandlerTrace_handlerTraceOf {ν : Type u} [VerificationModel ν]
    (handler : HandlerId) (handlers : List (Edge × HandlerId)) (bufs : SignedBuffers ν) :
    IsHandlerTrace handler handlers (handlerTraceOf handler handlers bufs) := by
  exact ⟨bufs, rfl⟩

/-- R.9 main theorem:
if handlers `h₁` and `h₂` both satisfy the same contract, their outcomes are
observationally equivalent. -/
theorem handler_equivalence {ν ε : Type u} [VerificationModel ν] [EffectRuntime ε]
    (contract : HandlerContract ν ε)
    (h₁ h₂ : HandlerId)
    (hSat₁ : HandlerModelsContract ν ε h₁ contract)
    (hSat₂ : HandlerModelsContract ν ε h₂ contract)
    (handlers : List (Edge × HandlerId))
    (bufs₁ bufs₂ : SignedBuffers ν) :
    ProtocolOutcome.ObservationalEq
      (contract.outcome (handlerTraceOf h₁ handlers bufs₁))
      (contract.outcome (handlerTraceOf h₂ handlers bufs₂)) := by
  refine contract.observationalDeterminism
    (handlerTraceOf h₁ handlers bufs₁)
    (handlerTraceOf h₂ handlers bufs₂)
    ?_ ?_
  · exact hSat₁ handlers _ (isHandlerTrace_handlerTraceOf h₁ handlers bufs₁)
  · exact hSat₂ handlers _ (isHandlerTrace_handlerTraceOf h₂ handlers bufs₂)
